export const API_URL = {
  LOGIN: '/api/auth/login',
  LOGOUT: '/api/auth/logout',
  FORGOTPASSWORD: '/api/auth/forgot-password',
  RESETPASSWORD: (token) => `/api/auth/reset-password?token=${token}`,
  CHANGE_PASSWORD: '/api/auth/change-pass',
  REGISTER: '/api/auth/register',
  PROFILE: '/api/auth/profile',
  CATEGORY_LIST: '/api/category/list',
  VERIFY_EMAIL: '/api/auth/send-verification-email',
  CATEGORY_READ: '/api/category/read',
  PRODUCT_LIST: '/api/product/list',
  PRODUCT_COLORS: '/api/product/listColor',
  PRODUCT_READ: '/api/product/read',
  PRODUCT_COMMENTS: '/api/product/comments',
  PRODUCT_HINT: '/api/product/hint',
  PROVINCE: '/api/location/province',
  CREATE_BILL: '/api/bill/create',
  PUSH_CART: '/api/users/pushCart',
  USER_BILL_LIST: '/api/users/bills',
  USER_NOTIFICATIONS: '/api/auth/notifications',
  BILL_LIST: '/api/bill/list',
  BILL_CALC: '/api/bill/calc',
  BILL_READ: '/api/bill/read',
  BILL_UPDATE: '/api/bill/update',
  PRODUCT_RATE: '/api/product/rate',
  TOP_PRODUCT: '/api/product/top',
  GET_OTP: '/api/auth/otp',
  CHECK_OTP: '/api/auth/checkOtp',
  UPDATE_INFO: '/api/users/update',
  UPDATE_CHANGE_PHONE: '/api/users/change-phone',
  DISTRICT: (proCode: string) => `/api/location/district/${proCode}`,
  WARD: (disCode: string) => `/api/location/ward/${disCode}`,
};
